Models/Worker.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjZes.Models
{
    public class Worker
    {
        public string Name { get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Pesel { get; set; }
        public bool IsApproved { get; set; }
        public string Ulica { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string NrDomu { get; set; }
    }
}

Controllers/WorkersController.cs
using DataORM;
using DataORM.Model;
using ProjZes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjZes.Controllers
{
    public class WorkersController : Controller
    {
        public ActionResult Index()
        {
            return View("~/Views/Workers/Index.cshtml");
        }

        [HttpPost]
        public ActionResult AddWorker(FormCollection form)
        {
            using (var context = new PetrolStationContext())
            {
                var worker = new DataORM.Model.Pracownik()
                {
                    Imie = form["userName"],
                    Nazwisko = form["userLastName"],
                    Pesel = form["pesel"],
                    CzyUprawniony = false,
                    Adres = new Adres()
                    {
                        Miasto = form["city"],
                        Ulica = form["street"],
                        Numer_domu = form["number"],
                        Kod_pocztowy = form["zipCode"]
                    }


                };
                if (form["uprawniony"] == "uprawniony")
                {
                    worker.CzyUprawniony = true;
                }

                context.Pracowniks.Add(worker);

                context.SaveChanges();
            }
            return WorkerManagement();
        }
        
        [HttpGet]
        public ActionResult WorkerManagement()
        {
            var workers = new List<Worker>();
            using (var context = new PetrolStationContext())
            {
                var pracownicy = context.Pracowniks.Where(x => x.CzyUsuniety == false).ToList();

                foreach (var worker in pracownicy)
                {
                    workers.Add(new Worker()
                    {
                        Pesel = worker.Pesel,
                        Name = worker.Imie,
                        LastName = worker.Nazwisko,
                        IsApproved = worker.CzyUprawniony,
                        Miasto = worker.Adres.Miasto,
                        Ulica = worker.Adres.Ulica,
                        KodPocztowy = worker.Adres.Kod_pocztowy,
                        NrDomu = worker.Adres.Numer_domu
                    });
                }
            }
            return View("WorkerManagement", workers);
        }

        [HttpGet]
        public ActionResult DeleteWorker(string pesel)
        {
            using (var context = new PetrolStationContext())
            {

                context
                    .Pracowniks
                    .Where(x => x.Pesel == pesel.ToString())
                    .SingleOrDefault()
                    .CzyUsuniety = true;

                context.SaveChanges();
            }

            return WorkerManagement();
        }

        [HttpPost]
        public ActionResult EditWorker(FormCollection form)
        {
            using (var context = new PetrolStationContext())
            {
                var pesel = form["pesel"];

                var worker = context.Pracowniks.Where(x => x.Pesel == pesel).FirstOrDefault();
                worker.Imie = form["name"];
                worker.Nazwisko = form["lname"];
                worker.Pesel = form["pesel"];
                worker.CzyUprawniony = form["role_id"] == "Uprawniony" ? true : false;
                worker.Adres.Miasto = form["city"];
                worker.Adres.Ulica = form["street"];
                worker.Adres.Numer_domu = form["streetnumber"];
                worker.Adres.Kod_pocztowy = form["postcode"];

                context.SaveChanges();
            }
            return WorkerManagement();
        }


    }
}

Views/Workers/Index.cshtml

<div class="row">

    <div class="col-lg-8 offset-lg-2">
        <div class="card mb-3">
            <div class="card-header">
                <h3><i class="fas fa-user-plus"></i> Dodaj pracownika</h3>

            </div>

            <div class="card-body">

                @using (Html.BeginForm("AddWorker", "Workers"))
                {
                    <div class="form-group">
                        <label for="userName">Imię<span class="text-danger">*</span></label>
                        <input type="text" name="userName" data-parsley-trigger="change" required placeholder="Wprowadź imię" class="form-control" id="userName">
                    </div>
                    <div class="form-group">
                        <label for="userLastName">Nazwisko<span class="text-danger">*</span></label>
                        <input type="text" name="userLastName" data-parsley-trigger="change" required placeholder="Wprowadź nazwisko" class="form-control" id="userLastName">
                    </div>
                    <div class="form-group">
                        <label for="pesel">PESEL<span class="text-danger">*</span></label>
                        <input id="pesel" name="pesel" type="text" placeholder="PESEL" required class="form-control">
                    </div>

                    <div class="form-group">
                        <label for="role">Czy uprawiony?</label>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="uprawniony" id="uprawniony" value="uprawniony" checked>
                            <label class="form-check-label" for="uprawniony">
                                Uprawniony
                            </label>
                        </div>
                        <div class="form-check">
                            <input class="form-check-input" type="radio" name="uprawniony" id="nieuprawniony" value="nieuprawniony">
                            <label class="form-check-label" for="nieuprawniony">
                                Nieuprawniony
                            </label>
                        </div>
                    </div>


                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary" type="submit">
                            Zatwierdź
                        </button>
                    </div>
                }


            </div>
        </div><!-- end card-->
    </div>
</div>

Views/Workers/WorkerManagement.cshtml
@model List<ProjZes.Models.Worker>

@{
	ViewBag.Title = "WorkerManagement";
}

<h2>Zarządzanie pracownikami</h2>



@*<div class="row">
	<div class="col-xl-12">
		<div class="breadcrumb-holder">
			<h1 class="main-title float-left">Breadcrumbs</h1>
			<div class="clearfix"></div>
		</div>
	</div>
</div>*@
<!-- end row -->



<div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">

		<div class="card mb-3">

			<div class="card-header">
				<span class="pull-right"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_add_user"><i class="fa fa-user-plus" aria-hidden="true"></i> Dodaj pracownika</button></span>
				<div class="modal fade custom-modal" tabindex="-1" role="dialog" aria-labelledby="modal_add_user" aria-hidden="true" id="modal_add_user">
					<div class="modal-dialog">
						<!--add user modal -->
						<div class="modal-content">

							@using (Html.BeginForm("AddWorker", "Workers"))
							{

								<div class="modal-header">
									<h5 class="modal-title">Dodaj pracownika</h5>
									<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								</div>

								<div class="modal-body">

									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Imię*</label>
												<input class="form-control" name="userName" type="text" required />
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<label>Nazwisko*</label>
												<input class="form-control" name="userLastName" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-12">
											<div class="form-group">
												<label>PESEL*</label>
												<input class="form-control" name="pesel" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>E-mail*</label>
												<input class="form-control" name="email" type="email" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Hasło*</label>
												<input class="form-control" name="password" type="text" required />
											</div>
										</div>
									</div>


									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Miasto*</label>
												<input class="form-control" name="city" type="text" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Kod pocztowy*</label>
												<input class="form-control" name="zipCode" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Ulica*</label>
												<input class="form-control" name="street" type="text" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Nr domu*</label>
												<input class="form-control" name="number" type="text" required />
											</div>
										</div>
									</div>


									<div class="row">
										<div class="form-group">
											<label for="role">Czy uprawiony?</label>
											<div class="form-check">
												<input class="form-check-input" type="radio" name="uprawniony" id="uprawniony" value="uprawniony" checked>
												<label class="form-check-label" for="uprawniony">
													Uprawniony
												</label>
											</div>
											<div class="form-check">
												<input class="form-check-input" type="radio" name="uprawniony" id="nieuprawniony" value="nieuprawniony">
												<label class="form-check-label" for="nieuprawniony">
													Nieuprawniony
												</label>
											</div>
										</div>

									</div>
									@*<div class="row">

			<div class="col-lg-12">
				<div class="form-group">
					<label>Rola</label>
					<select name="role_id" class="form-control" required>
						<option value="">- Wybierz-</option>
						<option value="1">Kierownik</option>
						<option value="2">Wyk. pracownik</option>
						<option value="3">Kasjer</option>

					</select>
				</div>
			</div>


		</div>*@
									@*<div class="form-group">
			<label>Avatar image (optional):</label> <br />
			<input type="file" name="image">
		</div>*@

								</div>

								<div class="modal-footer">
									<button class="btn btn-primary" type="submit">
										Zatwierdź
									</button>
								</div>

							}

							</div> <!-- end add user modal-->
					</div>
				</div> <!--modal fad-custom-->
				<h3><i class="fa fa-user"></i> Lista pracowników</h3>
			</div>
			<!-- end card-header -->

			<div class="card-body">


				<div class="table-responsive">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>PESEL</th>
								<th>Imię</th>
								<th>Nazwisko</th>
								<th>Miasto</th>
								<th>Kod pocztowy</th>
								<th>Ulica</th>
								<th>Numer domu</th>
								<th>Czy uprawniony</th>
								<th>Akcja</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var worker in Model)
							{

							<tr>

								<td class="pesel">@worker.Pesel</td>
								<td>@worker.Name</td>
								<td>@worker.LastName</td>
								<td>@worker.Miasto</td>
								<td>@worker.KodPocztowy</td>
								<td>@worker.Ulica</td>
								<td>@worker.NrDomu</td>
								<td>@(worker.IsApproved == true ? "Uprawniony" : "Nieuprawniony")</td>
								<!--Edit and remove -->
								<!--Here you should import data from SQL or other
	Remove: for example deleteRecord(ID_here)
	Edit worker:  all in div.modal-dialog  (6 lines below)S
	-->
								<td>
									<a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_edit_user"><i class="fas fa-edit" aria-hidden="true"></i></a>
									<a href="@Url.Action("DeleteWorker", "Workers", new{pesel=worker.Pesel})" class="btn btn-danger btn-sm" alt="Usuń pracownika" data-placement="top" data-toggle="tooltip" data-title="Delete"><i class="fas fa-trash" aria-hidden="true"></i></a>
									<div class="modal fade custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_edit_user">
										<div class="modal-dialog">
											<div class="modal-content">

												<form role="form" name="modalForm" action="@Url.Action("EditWorker", "Workers")" method="post">


													<div class="modal-header">
														<h5 class="modal-title">Edytuj</h5>
														<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
													</div>

													<div class="editmodal-body">

														<div class="modal-body">
															<div class="row">
																<div class="col-lg-12">
																	<div class="form-group">
																		<label>PESEL*</label>
																		<input class="form-control" name="pesel" id="pesel" value="96010112345" readonly />
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Imię*</label>
																		<input class="form-control" name="name" id="name" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Nazwisko*</label>
																		<input class="form-control" name="lname" id="lname" type="text" value="test" required />
																	</div>
																</div>
															</div>

															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Ulica*</label>
																		<input class="form-control" name="street" id="street" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Numer*</label>
																		<input class="form-control" name="streetnumber" id="streetnumber" type="text" value="test" required />
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Kod pocztowy*</label>
																		<input class="form-control" name="postcode" id="postcode" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Miasto*</label>
																		<input class="form-control" name="city" id="city" type="text" value="test" required />
																	</div>
																</div>
															</div>


															<div class="row">

																<div class="col-lg-12">
																	<div class="form-group">
																		<label>Rola</label>
																		<select name="role_id" id="role_id" class="form-control" required>
																			<option value="Uprawniony">Uprawniony</option>
																			<option value="Nieuprawniony">Nieuprawniony</option>

																		</select>
																	</div>
																</div>
															</div>


														</div>


														@*<div class="row">

				<div class="col-lg-12">
					<div class="form-group">
						<label>Rola</label>
						<select name="role_id" class="form-control" required>
							<option value="">- Wybierz-</option>
							<option value="1">Kierownik</option>
							<option value="2">Wyk. pracownik</option>
							<option selected="selected" value="3">Kasjer</option>

						</select>
					</div>
				</div>


			</div>*@
														@*<div class="form-group">
				<label>Avatar (opcjonalnie)</label> <br />
				<input type="file" name="image">
			</div>*@

													</div>

													<div class="modal-footer">
														<input type="hidden" name="user_id" id="user_id" value="5" />
														<button class="btn btn-primary edit-button">Edytuj</button>
													</div>

												</form>

											</div>
										</div>
								</td>
								<!--end edit and remove-->
							</tr>

							}
						</tbody>
					</table>
				</div>


			</div>
			<!-- end card-body -->

		</div>
		<!-- end card -->

	</div>
	<!-- end col -->

</div>
<!-- end row -->

@*<script>
		function deleteRecord(RecordId)
		{
			if (confirm('Confirm delete')) {
				window.location.href = '#';
			}
		}
</script>*@

<script>
	@*
	$(".btn[data-target='#modal_edit_user']").click(function () {
		var columnHeadings = $("thead th").map(function () {
			return $(this).text();
		}).get();
		columnHeadings.pop();
		var columnValues = $(this).parent().siblings().map(function () {
			return $(this).text();
		}).get();
		var modalBody = $('<div id="modalContent"></div>');
		var modalForm = $('<form role="form" name="modalForm" action="@Url.Action("EditWorker", "Workers")" method="post"></form>');
		$.each(columnHeadings, function (i, columnHeader) {


			
				var formGroup = $('<div class="form-row col-md-6"></div>');

				formGroup.append('<label for="' + columnHeader + '">' + columnHeader + '</label>');
				formGroup.append('<input class="form-control" name="' + columnHeader + '" id="' + columnHeader + '" value="' + columnValues[i] + '" />');
				modalForm.append(formGroup);
			


	   });
		modalBody.append(modalForm);
		$('.editmodal-body').html(modalBody);
	});
	$('.modal-footer .btn-primary').click(function () {
		$('form[name="modalForm"]').submit();
	})*@


	$(".btn[data-target='#modal_edit_user']").click(function () {
		var parent = $(this).closest('tr');
	   // var topic = parent.find('.topicAdd').attr('class').split(' ')[0];

		$('#pesel').val(parent.find('td:first-child').text());
		$('#name').val(parent.find('td:nth-child(2)').text());
		$('#lname').val(parent.find('td:nth-child(3)').text());
		$('#city').val(parent.find('td:nth-child(4)').text());
		$('#postcode').val(parent.find('td:nth-child(5)').text());
		$('#street').val(parent.find('td:nth-child(6)').text());
		$('#streetnumber').val(parent.find('td:nth-child(7)').text());
		$("#role_id").val(parent.find('td:nth-child(8)').text());
		$("#user_id").val(parent.find('td:first-child').text());


	});
	 $('.modal-footer .btn-primary').click(function () {
		$('form[name="modalForm"]').submit();
	});
</script>