Models/Customer.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ProjZes.Models
{
    public class Customer
    {
        public string Name{ get; set; }
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Pesel { get; set; }
        public string Ulica { get; set; }
        public string KodPocztowy { get; set; }
        public string Miasto { get; set; }
        public string NrDomu { get; set; }
    }
}

Controllers/CustomersController.cs
using DataORM;
using DataORM.Model;
using ProjZes.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ProjZes.Controllers
{
    public class CustomersController : Controller
    {
        public ActionResult Index()
        {
            return View("~/Views/Customers/Index.cshtml");
        }

        [HttpPost]
        public ActionResult AddCustomer(FormCollection form)
        {
            using (var context = new PetrolStationContext())
            {
                var client = new DataORM.Model.Klient()
                {
                    Imie = form["userName"],
                    Nazwisko = form["userLastName"],
                    Pesel = form["pesel"],
                    Adres = new Adres()
                    {
                        Miasto = form["city"],
                        Ulica = form["street"],
                        Kod_pocztowy = form["zipCode"],
                        Numer_domu = form["number"]
                    }

                };

                context.Klients.Add(client);

                
                context.SaveChanges();
            }
            return CustomerManagement();
        }

        [HttpGet]
        public ActionResult CustomerManagement()
        {
            var customers = new List<Customer>();
            using(var context = new PetrolStationContext())
            {
                var klienci = context.Klients.Where(x => x.CzyUsuniety == false).ToList();

                foreach (var customer in klienci)
                {
                    customers.Add(new Customer() {
                        Pesel = customer.Pesel,
                        Name = customer.Imie,
                        LastName = customer.Nazwisko,
                        Miasto = customer.Adres.Miasto,
                        Ulica = customer.Adres.Ulica,
                        KodPocztowy = customer.Adres.Kod_pocztowy,
                        NrDomu = customer.Adres.Numer_domu
                        
                    });
                }
            }

            return View("~/Views/Customers/CustomerManagement.cshtml", customers);
        }

        [HttpGet]
        public ActionResult DeleteCustomer(string pesel)
        {
            using (var context = new PetrolStationContext())
            {

                context
                    .Klients
                    .Where(x => x.Pesel == pesel.ToString())
                    .SingleOrDefault()
                    .CzyUsuniety = true;

                context.SaveChanges();
            }

            return CustomerManagement();
        }

        [HttpPost]
        public ActionResult EditCustomer(FormCollection form)
        {
            using (var context = new PetrolStationContext())
            {
                var pesel = form["pesel"];

                var customer = context.Klients.Where(x => x.Pesel == pesel).FirstOrDefault();
                customer.Imie = form["name"];
                customer.Nazwisko = form["lname"];
                customer.Pesel = form["pesel"];
                customer.Adres.Miasto = form["city"];
                customer.Adres.Ulica = form["street"];
                customer.Adres.Numer_domu = form["streetnumber"];
                customer.Adres.Kod_pocztowy = form["postcode"];

                context.SaveChanges();
            }
            return CustomerManagement();
        }

    }
}

Views/Customers/CustomerManagement.cshtml
@model List<ProjZes.Models.Customer>

<h2>Zarządzaj klientami</h2>




@*<div class="row">
		<div class="col-xl-12">
			<div class="breadcrumb-holder">
				<h1 class="main-title float-left">Users</h1>
				<div class="clearfix"></div>
			</div>
		</div>
	</div>*@
<!-- end row -->



<div class="row">

	<div class="col-xs-12 col-sm-12 col-md-12 col-lg-12 col-xl-12">

		<div class="card mb-3">

			<div class="card-header">
				<span class="pull-right"><button class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_add_user"><i class="fa fa-user-plus" aria-hidden="true"></i> Dodaj klienta</button></span>
				<div class="modal fade custom-modal" tabindex="-1" role="dialog" aria-labelledby="modal_add_user" aria-hidden="true" id="modal_add_user">
					<div class="modal-dialog">
						<!--add user modal -->
						<div class="modal-content">

							@using (Html.BeginForm("AddCustomer", "Customers"))
							{

								<div class="modal-header">
									<h5 class="modal-title">Dodaj klienta</h5>
									<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
								</div>

								<div class="modal-body">

									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Imię*</label>
												<input class="form-control" name="userName" type="text" required />
											</div>
										</div>
										<div class="col-lg-6">
											<div class="form-group">
												<label>Nazwisko*</label>
												<input class="form-control" name="userLastName" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-12">
											<div class="form-group">
												<label>PESEL*</label>
												<input class="form-control" name="pesel" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>E-mail*</label>
												<input class="form-control" name="email" type="email" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Hasło*</label>
												<input class="form-control" name="password" type="text" required />
											</div>
										</div>
									</div>

									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Miasto*</label>
												<input class="form-control" name="city" type="text" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Kod pocztowy*</label>
												<input class="form-control" name="zipCode" type="text" required />
											</div>
										</div>
									</div>
									<div class="row">
										<div class="col-lg-6">
											<div class="form-group">
												<label>Ulica*</label>
												<input class="form-control" name="street" type="text" required />
											</div>
										</div>

										<div class="col-lg-6">
											<div class="form-group">
												<label>Numer domu*</label>
												<input class="form-control" name="number" type="text" required />
											</div>
										</div>
									</div>

									@*<div class="row">

											<div class="col-lg-12">
												<div class="form-group">
													<label>Rola</label>
													<select name="role_id" class="form-control" required>
														<option value="">- Wybierz-</option>
														<option value="1">Kierownik</option>
														<option value="2">Wyk. pracownik</option>
														<option value="3">Kasjer</option>

													</select>
												</div>
											</div>


										</div>*@
									@*<div class="form-group">
											<label>Avatar image (optional):</label> <br />
											<input type="file" name="image">
										</div>*@

								</div>

								<div class="modal-footer">
									<button class="btn btn-primary" type="submit">
										Zatwierdź
									</button>
								</div>

							}

						</div> <!-- end add user modal-->
					</div>
				</div> <!--modal fad-custom-->
				<h3><i class="fa fa-user"></i> Lista klientów</h3>
			</div>
			<!-- end card-header -->

			<div class="card-body">


				<div class="table-responsive">
					<table class="table table-bordered">
						<thead>
							<tr>
								<th>PESEL</th>
								<th>Imię</th>
								<th>Nazwisko</th>
								<th>Miasto</th>
								<th>Kod pocztowy</th>
								<th>Ulica</th>
								<th>Numer domu</th>
								<th>Akcja</th>
							</tr>
						</thead>
						<tbody>
							@foreach (var customer in Model)
							{

							<tr>

								<td class="pesel">@customer.Pesel</td>
								<td>@customer.Name</td>
								<td>@customer.LastName</td>
								<td>@customer.Miasto</td>
								<td>@customer.KodPocztowy</td>
								<td>@customer.Ulica</td>
								<td>@customer.NrDomu</td>
								<!--Edit and remove -->
								<!--Here you should import data from SQL or other
	Remove: for example deleteRecord(ID_here)
	Edit customer:  all in div.modal-dialog  (6 lines below)
	-->
								<td>
									<a href="#" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modal_edit_user"><i class="fas fa-edit" aria-hidden="true"></i></a>
									<a href="@Url.Action("DeleteCustomer", "Customers", new{pesel=customer.Pesel})" class="btn btn-danger btn-sm" alt="Usuń klienta" data-placement="top" data-toggle="tooltip" data-title="Delete"><i class="fas fa-trash" aria-hidden="true"></i></a>
									<div class="modal fade custom-modal" tabindex="-1" role="dialog" aria-hidden="true" id="modal_edit_user">
										<div class="modal-dialog">
											<div class="modal-content">

												<form role="form" name="modalForm" action="@Url.Action("EditCustomer", "Customers")" method="post" enctype="multipart/form-data">
												  
														<div class="modal-header">
															<h5 class="modal-title">Edytuj</h5>
															<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
														</div>

														<div class="modal-body">

															<div class="row">
																<div class="col-lg-12">
																	<div class="form-group">
																		<label>PESEL*</label>
																		<input class="form-control" name="pesel" id="pesel" value="96010112345" readonly />
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Imię*</label>
																		<input class="form-control" name="name" id="name" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Nazwisko*</label>
																		<input class="form-control" name="lname" id="lname" type="text" value="test" required />
																	</div>
																</div>
															</div>

															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Ulica*</label>
																		<input class="form-control" name="street" id="street" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Numer*</label>
																		<input class="form-control" name="streetnumber" id="streetnumber" type="text" value="test" required />
																	</div>
																</div>
															</div>
															<div class="row">
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Kod pocztowy*</label>
																		<input class="form-control" name="postcode" id="postcode" type="text" value="test" required />
																	</div>
																</div>
																<div class="col-lg-6">
																	<div class="form-group">
																		<label>Miasto*</label>
																		<input class="form-control" name="city" id="city" type="text" value="test" required />
																	</div>
																</div>
															</div>


															@*<div class="row">

			<div class="col-lg-12">
				<div class="form-group">
					<label>Rola</label>
					<select name="role_id" class="form-control" required>
						<option value="">- Wybierz-</option>
						<option value="1">Kierownik</option>
						<option value="2">Wyk. pracownik</option>
						<option selected="selected" value="3">Kasjer</option>

					</select>
				</div>
			</div>


		</div>
		<div class="form-group">
			<label>Avatar (opcjonalnie)</label> <br />
			<input type="file" name="image">
		</div>*@

														</div>

														<div class="modal-footer">
															<input type="hidden" name="user_id" id="user_id" value="5" />
															<button class="btn btn-primary edit-button">Edytuj</button>
														</div>

													</form>

</div>
										</div>
								</td>
								<!--end edit and remove-->
							</tr>

							}
						</tbody>
					</table>
				</div>


			</div>
			<!-- end card-body -->

		</div>
		<!-- end card -->

	</div>
	<!-- end col -->

</div>
<!-- end row -->

<script>
	   /* function deleteRecord(RecordId)
		{
			if (confirm('Confirm delete')) {
				window.location.href = '#';
			}
		}*/

	$(".btn[data-target='#modal_edit_user']").click(function () {
		var parent = $(this).closest('tr');
	   // var topic = parent.find('.topicAdd').attr('class').split(' ')[0];

		$('#pesel').val(parent.find('td:first-child').text());
		$('#name').val(parent.find('td:nth-child(2)').text());
		$('#lname').val(parent.find('td:nth-child(3)').text());
		$('#city').val(parent.find('td:nth-child(4)').text());
		$('#postcode').val(parent.find('td:nth-child(5)').text());
		$('#street').val(parent.find('td:nth-child(6)').text());
		$('#streetnumber').val(parent.find('td:nth-child(7)').text());
		$("#role_id").val(parent.find('td:nth-child(8)').text());
		$("#user_id").val(parent.find('td:first-child').text());


	});
	 $('.modal-footer .btn-primary').click(function () {
		$('form[name="modalForm"]').submit();
	});
	
</script>

Views/Customers/Index.cshtml
@model ProjZes.Models.Customer

<div class="row">

    <div class="col-lg-8 offset-lg-2">
        <div class="card mb-3">
            <div class="card-header">
                <h3><i class="fas fa-user-plus"></i> Dodaj klienta</h3>

            </div>

            <div class="card-body">

                <div class="form-group">
                    <label for="userName">Rodzaj klienta<span class="text-danger">*</span></label>
                    <button id="radio1" type="button" class="btn btn-primary">Osoba prywatna</button>
                    <button id="radio2" type="button" class="btn btn-primary">Firma</button>
                </div>

                @using (Html.BeginForm("AddCustomer", "Customers"))
                {
                    <div class="form-group">
                        <label for="userName">Imię<span class="text-danger">*</span></label>
                        <input type="text" name="userName" data-parsley-trigger="change" required placeholder="Wprowadź imię" class="form-control" id="userName">
                    </div>
                    <div class="form-group">
                        <label for="userLastName">Nazwisko<span class="text-danger">*</span></label>
                        <input type="text" name="userLastName" data-parsley-trigger="change" required placeholder="Wprowadź nazwisko" class="form-control" id="userLastName">
                    </div>
                    <div class="form-group">
                        <label for="pesel">PESEL<span class="text-danger">*</span></label>
                        <input id="pesel" name="pesel" type="text" placeholder="PESEL" required class="form-control">
                    </div>


                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary" type="submit">
                            Zatwierdź
                        </button>
                    </div>
                }



                <!--Form dla firmy -->
                <form id="form2" action="#" data-parsley-validate novalidate>
                    <div class="form-group">
                        <label for="userName">Nazwa firmy<span class="text-danger">*</span></label>
                        <input type="text" name="nick" data-parsley-trigger="change" required placeholder="Wprowadź nazwę firmy" class="form-control" id="userName">
                    </div>
                    <div class="form-group">
                        <label for="userLastName">Adres<span class="text-danger">*</span></label>
                        <input type="text" name="nick" data-parsley-trigger="change" required placeholder="Wprowadź adres do faktury" class="form-control" id="userAddress">
                    </div>
                    <div class="form-group">
                        <label>NIP<span class="text-danger">*</span></label>
                        <div>
                            <input id="userNIP" data-parsley-type="number" type="text" class="form-control" required placeholder="Wprowadź NIP" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="emailAddress">Email adres<span class="text-danger">*</span></label>
                        <input type="email" name="email" data-parsley-trigger="change" required placeholder="Wprowadź e-mail" class="form-control" id="emailAddress">
                    </div>
                    <div class="form-group">
                        <label for="pass1">Hasło<span class="text-danger">*</span></label>
                        <input id="pass1" type="password" placeholder="Hasło" required class="form-control">
                    </div>
                    <div class="form-group text-right m-b-0">
                        <button class="btn btn-primary" type="submit">
                            Zatwierdź
                        </button>
                    </div>

                </form>
            </div>
        </div><!-- end card-->
    </div>
</div>